fix issue Add Fixed Height and Scroll to Search Dialog Result #77
jargonsdev/jargons.dev pull request #88
Opened 2024-08-24 13:35 UTC by jomefavourite

### Description

### Related Issue

### Screenshots/Screencasts

![image](https://github.com/user-attachments/assets/b4fc8d7c-5ad8-47f9-ae0a-d5e66df37bc3)

### Notes to Reviewer

2024-08-24 23:03 UTC, babblebey commented on src/components/islands/search.jsx
> +    <div className="block w-full text-sm md:text-base  max-h-[505px] overflow-y-scroll">
The maximum height (`max-h-**`) approach is great, exactly the thing that does it! But, I thought that the value of `505px` is a little rigid 🤔 

Take an instance where the viewport isn't even up to `505px` in size, the dialog would still enforce a `505px` hence shooting the div off the page... see screencast below 

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.08.24-23_50_52.webm](https://github.com/user-attachments/assets/fbee595f-bcb7-4a12-90ef-85e559b7470a)

### Here's what I would do 😉 

- Transfer the max-width styling to the parent div of both the search form and search result div, setting it to `max-h-full` i.e. `max-height: 100%` making sure that the child respects the available width.

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.08.24-23_58_26.webm](https://github.com/user-attachments/assets/7e2dba2e-3a52-474b-8a3b-e0cbde3321da)

2024-08-24 23:04 UTC, babblebey requested changes
Great stuff @jomefavourite,

Thank you for this one yea 😁, I've got some an observation, an improvement I think we can make 😉

2024-08-25 22:38 UTC, jomefavourite commented on src/components/islands/search.jsx
> +    <div className="block w-full text-sm md:text-base  max-h-[505px] overflow-y-scroll">
Alright, I'll make the changes

2024-09-10 07:20 UTC, jomefavourite commented
Hello @babblebey 
Apologies for the delay, I'll fix this today

2024-09-14 09:27 UTC, jomefavourite commented
@babblebey I've made the fix

2024-09-14 09:49 UTC, babblebey commented on src/components/islands/search.jsx
> +    <div className="block w-full text-sm md:text-base overflow-y-scroll">
```suggestion
    <div className="block w-full text-sm md:text-base overflow-y-scroll scrollbar">
```

We've got this utility class `scrollbar` that we use for our vertical scrollbar to make it some bit of uniform around the project. Let's use that here.

See it in action...

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.09.14-10_45_16.webm](https://github.com/user-attachments/assets/dfb650cc-7920-4a56-adb6-2c37b8a0da50)

2024-09-14 09:51 UTC, babblebey approved these changes
This looks great @jomefavourite ❤️ 

Thank you lots for this one. I'll approve this, but I'll wait for you to address the nits in review comment to improve this, then we merge 😁

2024-09-15 21:39 UTC, babblebey approved these changes

2024-09-15 21:40 UTC, merged